version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ent-grpc-prac-mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3333:3306"
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8080"
    depends_on:
      - mysql
